server:
  port: 8080
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:eniac
    username: eniac
    password: eniac
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
